### ISSUE TITLE
job descriptions truncated

### ISSUE THREAD

**Issue by katchia** [Bunsly/JobSpy#11]
Running into an issue where job descriptions are truncated when pulling them. Any idea why?

**Comment by cullenwatson** [comment]
The full job description requires another GET request as it's only visible from what I can see at each individual job posting url. Got it working for ZipRecruiter, going to add the others first before I merge.

**Comment by cullenwatson** [comment]
Issue resolved in PR #14

**Comment by atseng17** [comment]
Seems to be happening again, when pulling up 20 results, I saw some are truncated and some are not.

**Comment by cullenwatson** [comment]
@atseng17 yes, it was removed due to rate limiting as you have to send a request to each job posting to get the full description, significantly slowing the script down. Probably a better alternative is a flag to fetch the full description so that the people that just want the job titles/urls can quickly fetch them. What do you think?

**Comment by atseng17** [comment]
Got it! yeah that makes sense! Thank you for the immediate reply! Having the flexibility is nice. 

I imagine there will be ppl who want to get the full description, and for those ppl, they probably are okay with the slow down in fetching descriptions, while others who just need the titles, then don't really need the descriptions.
